-- Run this whole file once, in Supabase's SQL Editor.

-- 1) The table that holds every project.
create table if not exists projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content text not null,
  tags text[] not null default '{}',
  file_name text,
  file_path text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Row Level Security: turn it on, then only allow each signed-in user to
--    see and change their OWN rows.
alter table projects enable row level security;

create policy "select own projects"
on projects for select
using (auth.uid() = user_id);

create policy "insert own projects"
on projects for insert
with check (auth.uid() = user_id);

create policy "update own projects"
on projects for update
using (auth.uid() = user_id);

create policy "delete own projects"
on projects for delete
using (auth.uid() = user_id);

-- 3) Storage policies for uploaded .md/.txt files.
--    These only work AFTER you've created a bucket named "project-files"
--    in the Storage tab (see SETUP.md, Part 1). Files are stored under a
--    folder named after each user's id, so these policies keep everyone's
--    uploads private to themselves.
create policy "select own files"
on storage.objects for select
using (
  bucket_id = 'project-files'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "insert own files"
on storage.objects for insert
with check (
  bucket_id = 'project-files'
  and auth.uid()::text = (storage.foldername(name))[1]
);

create policy "delete own files"
on storage.objects for delete
using (
  bucket_id = 'project-files'
  and auth.uid()::text = (storage.foldername(name))[1]
);
